# Generated by Django 4.2.2 on 2024-07-30 06:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('flight_time', models.DurationField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aircraft')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='core.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='core.airport')),
            ],
            options={
                'db_table': 'core_flights',
                'ordering': ['created'],
            },
        ),
    ]
